language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    - PYTHONWARNINGS="default,ignore::PendingDeprecationWarning,ignore::ResourceWarning"
  matrix:
    - DB="POSTGRESQL"
    - DB="MYSQL"

sudo: false

cache:
  pip: true
  directories:
    - frontend/node_modules

addons:
  postgresql: '9.6'
  mysql: '5.5'
  apt:
    packages:
      - librrd-dev
      - rrdtool

services:
  - postgres
  - mysql

before_install:
  - pip install codecov
  - pip install -r test-requirements.txt
  - pip install -e git+https://github.com/modoboa/modoboa.git@1.x#egg=modoboa

install:
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - cd test_project
  - coverage run --source ../modoboa_radicale manage.py test modoboa_radicale

after_success:
  - codecov

before_deploy:
  - cd ../modoboa_radicale
  - django-admin compilemessages
  - cd ../frontend
  - nvm install --lts
  - npm install
  - npm run build
  - cd ..

deploy:
  provider: pypi
  user: tonio
  password:
    secure: HvFy7qHGFLRzHZzGQYb8miW7RD9hubkzT1P20Gd3U//BCS3Db9e3REiA2Y8ecnUfAHXRXFa1J8Wyq/ThbVTMo6UIIdkow9STDF88Bm/H8uPY9F/4qWefjelFA1C2Faxh1JDAEPmm1nkzVlGxBLQ25fvJPZflRt1jYBRY9ZSqaXg=
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.7'
    condition: "$DB = POSTGRESQL"
